controller, service init
711skhu/admin pull request #3
Opened 2019-04-05 02:22 UTC by yjll1019

필요한 Controller, Service 클래스 생성했습니다.

2019-04-05 03:41 UTC, shouwn approved these changes

2019-04-05 06:15 UTC, KimJye approved these changes

2019-04-05 07:31 UTC, 1eehyeji approved these changes

2019-04-05 17:10 UTC, songz1 approved these changes

2019-04-06 09:48 UTC, shouwn requested changes
저희가 Member 클래스가 있지만 이는 공통 부분을 모은 추상 클래스입니다.

공통 부분과 관련된 로직이 있어 MemberService를 만드는 것은 좋은 생각이지만 MemberController는 Admin과 Student의 URL 매핑이 다르기 때문에 Admin과 Student로 분리하는 게 좋을 것 같네요.

MemberService는 공통 부분을 가지고 있기 때문에 abstract class로 작성하여 AdminService와 StudentService가 상속하는 형식을 취하는 것이 좋을 거라 생각합니다. 

Member클래스만 사용하는 로직은 MemberService에 구현하고 Admin과 Student의 특징이 필요한 것은 abstract method를 만들어 추상화 하는 편이 좋을 것 같네요.

예를 들어 이 회원이 가입한지 확인하는 로직을 템플릿 메소드 패턴으로 구현하면 좋을 것 같네요.

그리고 순수 서비스 관련 클래스들은 core에 있는 것이 맞다고 생각하기 때문에 빼는 게 맞다고 생각합니다.

그 순수 서비스를 사용하는 클래스로 AdminServiceForAdmin 과 같은 클래스가 있으면 좋겠네요.

2019-04-09 10:14 UTC, KimJye approved these changes

2019-04-09 10:43 UTC, 1eehyeji approved these changes

2019-04-09 14:12 UTC, shouwn commented
entity 와 통일성을 맞추기 위해
service - member
service - problem 
형식으로 패키지를 작성해주세요

2019-04-10 05:34 UTC, KimJye approved these changes

2019-04-10 06:04 UTC, songz1 approved these changes

2019-04-10 08:19 UTC, shouwn approved these changes

2019-04-10 08:31 UTC, 1eehyeji approved these changes

2019-04-11 01:34 UTC, songz1 approved these changes

2019-04-14 04:28 UTC, merged